repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./project_configs/.isort.cfg .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config ./project_configs/.black .
        language: system
        types: [python]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config ./project_configs/.flake8 .
        language: system
        types: [python]
        pass_filenames: false